name: build

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  job1:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          apt-get update
          apt install -y build-essential
      - run: |
          cd /home/runner/work/Orin_CM4
          g++ orion_receaver.cpp  -lwiringPi -o b.out
          g++ orion_comunication_core.cpp  -lwiringPi -o a.out
