name: build

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  job1:
    name: build
    runs-on: ubuntu-22.04
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
      - run: |
          cd /home/runner/work/Orion_CM4
          ls -R
          g++ ./orion_receaver.cpp  -lwiringPi -o b.out
          g++ ./orion_comunication_core.cpp  -lwiringPi -o a.out
